config/routes.rb
Rails.application.routes.draw do

  get "home", to: "home#home"

  get "password", to: "password#edit", as: "edit_password"
  patch "password", to: "password#update"
  post "password", to: "password#create"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  get "password/reset", to: "password_reset#new"
  post "password/reset", to: "password_reset#create"

  get "password/reset/edit", to: "password_reset#edit"
  patch "password/reset/edit", to: "password_reset#update"

  get "profile/edit", to: "profile#edit"
  patch "profile/edit", to: "profile#update"
  post "profile/edit", to: "profile#create"

  resources :menu, only: [:new, :create, :edit, :update, :destroy]
  get '/menu', to: 'menu#index', as: 'menu_indx'
  get '/menu/:category_id', to: 'menu#category', as: :menu_category

  get 'categories', to: 'categories#index'

  post 'add_to_cart', to: 'items#add_to_cart', as: :add_to_cart
  
  resource :cart, only: [:show] do
    delete 'clear', on: :collection
    post 'remove_one', on: :collection
  end

  resources :orders, only: [:create, :index, :show]
  patch 'orders/:id/cancel', to: 'orders#cancel', as: :cancel_order
  delete 'orders/:id', to: 'orders#destroy', as: :delete_order
  patch 'orders/:order_id/items/:id/update_quantity', to: 'orders#update_quantity', as: :update_order_item_quantity
  delete 'orders/:order_id/items/:item_id', to: 'orders#destroy_item', as: :delete_order_item
  patch 'orders/:id/update_status', to: 'orders#update_status', as: :update_order_status

  root 'home#home'
=begin
  match '*path', to: 'home#home', via: :all
=end
end

app/models/menu.rb
class Menu < ApplicationRecord
  self.table_name = "menu"
  attr_accessor :image_base64
  belongs_to :category


end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  before_action :require_admin, only: [:new, :create, :edit, :update, :destroy]
  def index
    if Current.user&.admin?
      @menu_items = Menu.all
    else
      @menu_items = Menu.where(can_be_prepared: true)
    end
    @menu_items.each do |item|
      item.image_base64 = Base64.encode64(item.image)
    end
  end
  def category
    @category_id = params[:category_id]
    if Current.user&.admin?
      @menu_items = Menu.where(category_id: @category_id)
    else
      @menu_items = Menu.where(category_id: @category_id, can_be_prepared: true)
    end
    @menu_items.each do |item|
      item.image_base64 = Base64.encode64(item.image)
    end
    render 'index'
  end
  def edit
    @menu_item = Menu.find(params[:id])
  end
  def update
    @menu_item = Menu.find(params[:id])

    if @menu_item.update(menu_params)
      image_data = params[:menu][:image]
      if image_data.present?
        new_image_data = image_data.read
        @menu_item.image = new_image_data
        @menu_item.save
      end

      redirect_to menu_path, notice: "Menu item updated successfully!"
    else
      render :edit
    end
  end

  def new
    @menu_item = Menu.new
  end

  def create
    @menu_item = Menu.new(menu_params)

    image_data = params[:menu][:image]

    @menu_item.image = image_data.read if image_data.present?

    if @menu_item.save
      redirect_to menu_path, notice: "Menu item added successfully!"
    else
      render :new
    end
  end
  def destroy
    @menu_item = Menu.find(params[:id])
    @menu_item.destroy
    redirect_to categories_path, notice: "Menu item deleted successfully!"
  end

  private

  def menu_params
    params.require(:menu).permit(:item_name, :description, :price, :category_id, :can_be_prepared, :image)
  end
  def require_admin
    unless Current.user&.admin?
      flash[:alert] = "You don't have permission to access this page."
      redirect_to home_path
    end
  end
  
end

app/views/menu/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card border-0 shadow">
        <div class="card-header bg-dark text-white text-center py-3">
          <h1 class="m-0">Edit Menu Item</h1>
        </div>
        <div class="card-body p-4">
          <%= form_with(model: @menu_item, url: menu_path(@menu_item), local: true) do |form| %>
            <div class="mb-3">
              <%= form.label :item_name, class: "form-label" %>
              <%= form.text_field :item_name, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :description, class: "form-label" %>
              <%= form.text_area :description, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :price, class: "form-label" %>
              <%= form.number_field :price, class: "form-control", step: "0.01" %>
            </div>
            <div class="mb-3">
              <%= form.label :category_id, class: "form-label" %>
              <%= form.select :category_id, options_for_select(Category.pluck(:category_name, :category_id)), {}, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :can_be_prepared, class: "form-label" %>
              <%= form.check_box :can_be_prepared, class: "form-check-input" %>
            </div>
            <div class="mb-3">
              <%= form.label :image, class: "form-label" %>
              <%= form.file_field :image, class: "form-control", accept: "image/jpg" %>
            </div>
            <%= form.submit "Update Menu Item", class: "btn btn-primary btn-block" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/menu/index.html.erb
<div class="container ">
  <div class="row justify-content-center">
    <div class="">
      <div class="card border-0 shadow-lg">
        <div class="card-header bg-dark text-white text-center py-3">
          <h1 class="m-0">Menu</h1>
        </div>
        <div class="row menu-items align-items-stretch p-4">
          <% @menu_items.each do |item| %>
            <div class="col-lg-4 p-3">
              <div class="card h-100 shadow-sm border-0">
                <div class="menu-item-image">
                  <% if Current.user&.admin? %>
                    <%= link_to edit_menu_path(item), method: :get do %>
                      <%= image_tag("data:image/png;base64,#{item.image_base64}", alt: "Menu Item Image", class: "img-fluid rounded-top") if item.image_base64.present? %>
                    <% end %>
                  <% else %>
                    <%= image_tag("data:image/jpg;base64,#{item.image_base64}", alt: "Menu Item Image", class: "img-fluid rounded-top") if item.image_base64.present? %>
                  <% end %>
                </div>
                <div class="card-body d-flex flex-column justify-content-between">
                  <div>
                    <% if Current.user&.admin? %>
                      <%= link_to edit_menu_path(item), class: "stretched-link text-decoration-none text-dark", method: :get do %>
                        <h2 class="card-title text-center"><%= item.item_name %></h2>
                      <% end %>
                    <% else %>
                      <h2 class="card-title text-center"><%= item.item_name %></h2>
                    <% end %>
                    <p class="card-text text-center text-muted"><%= item.description %></p>
                  </div>
                  <div class="text-center">
                    <p class="card-text mt-2"><strong>Price:</strong> <%= item.price %><strong>$</strong></p>
                    <% unless Current.user&.admin? %>
                      <%= button_to 'Add to cart', add_to_cart_path(item_id: item.id), class: "btn btn-outline-success mt-2", remote: true, method: :post %>
                    <% end %>
                    <% if Current.user&.admin? %>
                      <%= button_to 'Delete', menu_path(item), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm mt-2' %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/menu/new.html.erb
<div class="container ">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card border-0 shadow">
        <div class="card-header bg-dark text-white text-center py-3">
          <h1 class="m-0">Add New Menu Item</h1>
        </div>
        <div class="card-body p-3">
          <%= form_with(model: @menu_item, url: menu_index_path, local: true) do |form| %>
            <div class="mb-3">
              <%= form.label :item_name, class: "form-label" %>
              <%= form.text_field :item_name, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :description, class: "form-label" %>
              <%= form.text_area :description, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :price, class: "form-label" %>
              <%= form.number_field :price, class: "form-control", step: "0.01" %>
            </div>
            <div class="mb-3">
              <%= form.label :category_id, class: "form-label" %>
              <%= form.select :category_id, options_for_select(Category.pluck(:category_name, :category_id)), {}, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= form.label :can_be_prepared, class: "form-label" %>
              <%= form.check_box :can_be_prepared, class: "form-check-input" %>
            </div>
            <div class="mb-3">
              <%= form.label :image, class: "form-label" %>
              <%= form.file_field :image, class: "form-control", accept: "image/jpg" %>
            </div>
            <%= form.submit "Add Menu Item", class: "btn btn-primary btn-block" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>