config/routes.rb
Rails.application.routes.draw do

  get "home", to: "home#home"

  get "password", to: "password#edit", as: "edit_password"
  patch "password", to: "password#update"
  post "password", to: "password#create"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  get "password/reset", to: "password_reset#new"
  post "password/reset", to: "password_reset#create"

  get "password/reset/edit", to: "password_reset#edit"
  patch "password/reset/edit", to: "password_reset#update"

  get "profile/edit", to: "profile#edit"
  patch "profile/edit", to: "profile#update"
  post "profile/edit", to: "profile#create"

  resources :menu, only: [:new, :create, :edit, :update, :destroy]
  get '/menu', to: 'menu#index', as: 'menu_indx'
  get '/menu/:category_id', to: 'menu#category', as: :menu_category

  get 'categories', to: 'categories#index'

  post 'add_to_cart', to: 'items#add_to_cart', as: :add_to_cart
  
  resource :cart, only: [:show] do
    delete 'clear', on: :collection
    post 'remove_one', on: :collection
  end

  resources :orders, only: [:create, :index, :show]
  patch 'orders/:id/cancel', to: 'orders#cancel', as: :cancel_order
  delete 'orders/:id', to: 'orders#destroy', as: :delete_order
  patch 'orders/:order_id/items/:id/update_quantity', to: 'orders#update_quantity', as: :update_order_item_quantity
  delete 'orders/:order_id/items/:item_id', to: 'orders#destroy_item', as: :delete_order_item
  patch 'orders/:id/update_status', to: 'orders#update_status', as: :update_order_status

  root 'home#home'
=begin
  match '*path', to: 'home#home', via: :all
=end
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4 card w-50 container-fluid text-center" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-warning mt-4 card w-50 container-fluid text-center" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg" style="">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="/home">
      AlcoMarket</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav container-fluid justify-content-center">
        <a class="nav-link text-warning<%= 'active text-white' if current_page?(home_path) %>" href="/home">Home</a>
        <a class="nav-link text-warning<%= 'active text-white' if current_page?(categories_path) %>" href="/categories">Menu</a>
        <% if Current.user && Current.user.role != 'admin' %>
          <a class="nav-link text-warning<%= 'active text-white' if current_page?(profile_edit_path) %>" href="/profile/edit">Profile</a>
          <a class="nav-link text-warning<%= 'active text-white' if current_page?(orders_path) %>" href="/orders">Orders</a>
        <% end %>
        <% if Current.user && Current.user.admin? %>
          <a class="nav-link text-warning <%= 'active text-white' if current_page?(orders_path) %>" href="/orders">Orders</a>
          <a class="nav-link text-warning<%= 'active text-white' if current_page?(new_menu_path) %>" href="/menu/new">Add Alcohol</a>
        <% end %>
      </div>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 gap-1 ">
        <% if Current.user %>
          <% if Current.user.role != 'admin' %>
            <a class="navbar-brand text-warninig" href="/cart">
              <img src="https://cdn-icons-png.freepik.com/512/275/275790.png" alt="Bootstrap" width="30" height="30">
            </a>
          <% end %>
          <li class="nav-item">
            <%= link_to Current.user.email, edit_password_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-warning" %>
          </li>
        <% else %>
          <a class="navbar-brand" href="/cart">
            <img src="https://cdn-icons-png.freepik.com/512/275/275790.png" alt="Bootstrap" width="30" height="30">
          </a>
          <li class="nav-item d-flex justify-content-center align-items-center">
            <%= link_to "Login", sign_in_path, class: "btn btn-outline-warning mx-auto btn-block" %>
          </li>
          <br>
          <li class="nav-item d-flex justify-content-center align-items-center">
            <%= link_to "Sing Up", sign_up_path, class: "btn btn-outline-warning ", style: "width: 90px;" %>
          </li>
          <br>
        <% end %>
      </ul>

    </div>
  </div>
</nav>