config/routes.rb
Rails.application.routes.draw do

  get "home", to: "home#home"

  get "password", to: "password#edit", as: "edit_password"
  patch "password", to: "password#update"
  post "password", to: "password#create"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  get "password/reset", to: "password_reset#new"
  post "password/reset", to: "password_reset#create"

  get "password/reset/edit", to: "password_reset#edit"
  patch "password/reset/edit", to: "password_reset#update"

  get "profile/edit", to: "profile#edit"
  patch "profile/edit", to: "profile#update"
  post "profile/edit", to: "profile#create"

  resources :menu, only: [:new, :create, :edit, :update, :destroy]
  get '/menu', to: 'menu#index', as: 'menu_indx'
  get '/menu/:category_id', to: 'menu#category', as: :menu_category

  get 'categories', to: 'categories#index'

  post 'add_to_cart', to: 'items#add_to_cart', as: :add_to_cart
  
  resource :cart, only: [:show] do
    delete 'clear', on: :collection
    post 'remove_one', on: :collection
  end

  resources :orders, only: [:create, :index, :show]
  patch 'orders/:id/cancel', to: 'orders#cancel', as: :cancel_order
  delete 'orders/:id', to: 'orders#destroy', as: :delete_order
  patch 'orders/:order_id/items/:id/update_quantity', to: 'orders#update_quantity', as: :update_order_item_quantity
  delete 'orders/:order_id/items/:item_id', to: 'orders#destroy_item', as: :delete_order_item
  patch 'orders/:id/update_status', to: 'orders#update_status', as: :update_order_status

  root 'home#home'
=begin
  match '*path', to: 'home#home', via: :all
=end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'

  validates :user_id, presence: true
  validates :added_items_data, presence: true
  validates :total_amount, presence: true
  validates :status, presence: true



  attribute :added_items_data, :jsonb
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :require_user_logged_in!
  before_action :require_user_profile, only: [:create]

  def create
    cart_items = session[:cart].map { |item_id, quantity| { item_id: item_id.to_i, quantity: quantity.to_i } }
    total_amount = calculate_total_amount(cart_items)

    if Current.user
      @order = Current.user.orders.build(
        added_items_data: cart_items.to_json,
        total_amount: total_amount,
        status: "pending"
      )
    end

    if @order.save
      session.delete(:cart)
      redirect_to orders_path, notice: 'Order placed successfully!'
    else
      redirect_to cart_path, alert: "Failed to place order! #{order.errors.full_messages.join(', ')}"
    end
  end

  def cancel
    @order = Order.find(params[:id])
    if @order.update(status: 'canceled')
      redirect_to orders_path, notice: 'Order canceled successfully!'
    else
      redirect_to @order, alert: 'Failed to cancel order.'
    end
  end

  def update_status
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to @order, notice: 'Order status updated successfully!'
    else
      redirect_to @order, alert: 'Failed to update order status.'
    end
  end

  def destroy_item
    @order = Order.find(params[:order_id])
    items = JSON.parse(@order.added_items_data)

    if items.length > 1
      item = items.find { |i| i['item_id'] == params[:item_id].to_i }
      if item
        item_price = item_price(item['item_id'])
        old_quantity = item['quantity'].to_i

        items.delete(item)
        @order.update(added_items_data: items.to_json)
        @order.total_amount -= old_quantity * item_price

        if @order.save
          redirect_to @order, notice: 'Item removed from order successfully!'
        else
          redirect_to @order, alert: 'Failed to save order after removing item.'
        end
      else
        redirect_to @order, alert: 'Failed to remove item from order.'
      end
    else
      redirect_to @order, alert: 'Cannot remove the last item from the order.'
    end
  end


  def update_quantity
    @order = Order.find(params[:order_id])
    items = JSON.parse(@order.added_items_data)

    item_to_update = items.find { |item| item['item_id'] == params[:id].to_i }

    if item_to_update
      old_quantity = item_to_update['quantity'].to_i
      new_quantity = params[:item][:quantity].to_i

      item_to_update['quantity'] = new_quantity
      @order.added_items_data = items.to_json

      @order.total_amount -= old_quantity * item_price(item_to_update['item_id'])
      @order.total_amount += new_quantity * item_price(item_to_update['item_id'])

      @order.status = 'pending'

      if @order.save
        redirect_to @order, notice: 'Item quantity updated successfully!'
      else
        redirect_to @order, alert: 'Failed to save order after updating item quantity'
      end
    else
      redirect_to @order, alert: 'Failed to update item quantity. Item not found in order.'
    end
  end
  def index
    @order_statuses = { 'pending' => 'pending', 'confirmed' => 'confirmed', 'shipped' => 'shipped', 'delivered' => 'delivered', 'canceled' => 'canceled' }
    if Current.user.admin?
      @orders = Order.all
      @orders = @orders.where(status: params[:status]) if params[:status].present?
      @orders = @orders.where("order_date >= ?", params[:start_date]) if params[:start_date].present?
      @orders = @orders.where("order_date <= ?", params[:end_date]) if params[:end_date].present?
      @orders = @orders.where("total_amount >= ?", params[:min_amount]) if params[:min_amount].present?
      @orders = @orders.where("total_amount <= ?", params[:max_amount]) if params[:max_amount].present?
      render 'admin_index'
    else
      @orders = Order.where(user_id: Current.user.id)
      @orders = @orders.where(status: params[:status]) if params[:status].present?
      @orders = @orders.where("order_date >= ?", params[:start_date]) if params[:start_date].present?
      @orders = @orders.where("order_date <= ?", params[:end_date]) if params[:end_date].present?
      @orders = @orders.where("total_amount >= ?", params[:min_amount]) if params[:min_amount].present?
      @orders = @orders.where("total_amount <= ?", params[:max_amount]) if params[:max_amount].present?
    end
  end

  def show
    @order = Order.find_by(order_id: params[:id])
    @order_statuses = { 'pending' => 'pending', 'confirmed' => 'confirmed', 'shipped' => 'shipped', 'delivered' => 'delivered' }

    if @order
      if Current.user.admin? || @order.user_id == Current.user.id
        @added_items_data = JSON.parse(@order.added_items_data.gsub('\"', '"'))
        @items_with_images = @added_items_data.map do |item|
          menu_item = Menu.find(item['item_id'])
          {
            'item_id' => item['item_id'],
            'quantity' => item['quantity'],
            'name' => menu_item.item_name,
            'price' => menu_item.price,
            'image_base64' => Base64.encode64(menu_item.image)
          }
        end
      else
        redirect_to orders_path, alert: "You are not authorized to view this order."
      end
    else
      redirect_to orders_path, alert: "Order not found."
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path, notice: 'Order was successfully deleted.'
  end

  private
  def item_price(item_id)
    item = Menu.find_by(item_id: item_id)
    item.price if item
  end

  def order_params
    params.require(:order).permit(:status)
  end

  def require_user_profile
    unless Current.user.user_profile.present?
      redirect_to profile_edit_path, alert: "Please fill in your profile before placing an order."
    end
  end

  def calculate_total_amount(items)
    total_amount = 0

    items.each do |item|
      menu_item = Menu.find_by(item_id: item[:item_id])
      if menu_item
        total_amount += menu_item.price * item[:quantity]
      else
        puts "Menu item with id #{item[:item_id]} not found."
      end
    end

    total_amount
  end

end

app/views/orders/admin_index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="">
      <div class="card border-0">
        <div class="card-header bg-dark text-white text-center">
          <h1>Orders</h1>
        </div>
        <div class="card-body">
          <%= form_tag orders_path, method: :get, class: "row justify-content-center" do %>
            <div class="col-md-6 mb-3">
              <%= label_tag :status, "Filter by Status:", class: "form-label" %>
              <%= select_tag :status, options_for_select(@order_statuses.map { |key, value| [value.capitalize, key] }), { include_blank: true, class: "form-select" } %>
            </div>
            <div class="col-md-6 mb-3">
              <%= label_tag :start_date, "Start Date:", class: "form-label" %>
              <%= date_field_tag :start_date, params[:start_date], class: "form-control" %>
            </div>
            <div class="col-md-6 mb-3">
              <%= label_tag :end_date, "End Date:", class: "form-label" %>
              <%= date_field_tag :end_date, params[:end_date], class: "form-control" %>
            </div>
            <div class="col-md-6 mb-3">
              <%= label_tag :min_amount, "Min Amount ($):", class: "form-label" %>
              <%= number_field_tag :min_amount, params[:min_amount], class: "form-control" %>
            </div>
            <div class="col-md-6 mb-3">
              <%= label_tag :max_amount, "Max Amount ($):", class: "form-label" %>
              <%= number_field_tag :max_amount, params[:max_amount], class: "form-control" %>
            </div>
            <div class="col-md-12 mb-3 text-center">
              <%= submit_tag "Apply Filter", class: "btn btn-primary w-50" %>
            </div>
          <% end %>

          <% if @orders.any? %>
            <div class="table-responsive">
              <table class="table table-hover">
                <thead class="thead-dark">
                <tr>
                  <th class="text-center" scope="col">Order ID</th>
                  <th class="text-center" scope="col">User ID</th>
                  <th class="text-center" scope="col">Total Amount</th>
                  <th class="text-center" scope="col">Order Date</th>
                  <th class="text-center" scope="col">Status</th>
                  <th class="text-center" scope="col">Info</th>
                  <th class="text-center" scope="col">Delete</th>
                </tr>
                </thead>
                <tbody>
                <% @orders.each do |order| %>
                  <tr>
                    <td class="text-center"><%= order.order_id %></td>
                    <td class="text-center"><%= order.user_id %></td>
                    <td class="text-center">$<%= order.total_amount %></td>
                    <td class="text-center"><%= order.order_date.strftime("%B %d, %Y %H:%M") %></td>
                    <td class="text-center"><%= order.status %></td>
                    <td class="text-center">
                      <%= link_to order_path(order), class: "btn btn-outline-info btn-sm" do %>
                        Details
                      <% end %>
                    </td>
                    <td class="text-center">
                      <%= form_for(order, method: :delete, url: order_path(order), data: { confirm: 'Are you sure?' }) do |f| %>
                        <%= f.submit 'Delete', class: 'btn btn-outline-danger btn-sm' %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
                </tbody>
              </table>
            </div>
          <% else %>
            <div class="container text-center">
              <p class="mt-4">No orders found</p>
            </div>
          <% end %>

          <div class="container text-center">
            <div class="mt-3 mb-3">
              <%= link_to 'Back', home_path, class: "btn btn-secondary" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="">
      <div class="card border-0">
        <div class="card-header bg-dark text-white text-center">
          <h1>Orders</h1>
        </div>
        <div class="card-body">
          <%= form_tag orders_path, method: :get, class: "row justify-content-center" do %>
            <div class="col-md-6 mb-3">
              <%= label_tag :status, "Filter by Status:", class: "form-label" %>
              <%= select_tag :status, options_for_select(@order_statuses.map { |key, value| [value.capitalize, key] }), { include_blank: true, class: "form-select" } %>
            </div>
            <div class="col-md-6 mb-3">
              <%= label_tag :start_date, "Start Date:", class: "form-label" %>
              <%= date_field_tag :start_date, params[:start_date], class: "form-control" %>
            </div>
            <div class="col-md-6 mb-3">
              <%= label_tag :end_date, "End Date:", class: "form-label" %>
              <%= date_field_tag :end_date, params[:end_date], class: "form-control" %>
            </div>
            <div class="col-md-6 mb-3">
              <%= label_tag :min_amount, "Min Amount ($):", class: "form-label" %>
              <%= number_field_tag :min_amount, params[:min_amount], class: "form-control" %>
            </div>
            <div class="col-md-6 mb-3">
              <%= label_tag :max_amount, "Max Amount ($):", class: "form-label" %>
              <%= number_field_tag :max_amount, params[:max_amount], class: "form-control" %>
            </div>
            <div class="col-md-12 mb-3 text-center">
              <%= submit_tag "Apply Filter", class: "btn btn-primary w-50" %>
            </div>
          <% end %>

          <% if @orders.any? %>
            <div class="table-responsive">
              <table class="table table-hover">
                <thead class="thead-dark">
                <tr>
                  <th class="text-center" scope="col">Order ID</th>
                  <th class="text-center" scope="col">Total Amount</th>
                  <th class="text-center" scope="col">Order Date</th>
                  <th class="text-center" scope="col">Status</th>
                  <th class="text-center" scope="col">Info</th>
                </tr>
                </thead>
                <tbody>
                <% @orders.each do |order| %>
                  <tr>
                    <td class="text-center"><%= order.order_id %></td>
                    <td class="text-center">$<%= order.total_amount %></td>
                    <td class="text-center"><%= order.order_date.strftime("%B %d, %Y %H:%M") %></td>
                    <td class="text-center"><%= order.status %></td>
                    <td class="text-center">
                      <%= link_to order_path(order), class: "btn btn-outline-info btn-sm" do %>
                        Details
                      <% end %>
                    </td>
                  </tr>
                <% end %>
                </tbody>
              </table>
            </div>

          <% else %>
            <div class="container text-center">
              <p class="mt-4">No orders found</p>
              <div class="mt-3 mb-3">
                <%= link_to 'Back', home_path, class: "btn btn-secondary" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="">
      <div class="card border-0">
        <div class="card-header bg-dark text-white text-center">
          <h1>Order Details</h1>
        </div>
        <div class="card-body">
          <% if @order %>
            <div class="row">
            <% @items_with_images.each do |item| %>
              <div class="p-2 col-lg-4 col-md-6 col-sm-12">
                <div class="card shadow">
                  <div class="card-body">
                    <div class="menu-item-image">
                    <%= image_tag("data:image/png;base64,#{item['image_base64']}", alt: "Menu Item Image", class: "img-fluid rounded-top menu-item-image") %>
                    </div>
                    <h2 class="card-title mt-3 mb-2"><%= item['name'] %></h2>
                    <p class="card-text mb-2">Quantity: <%= item['quantity'] %></p>
                    <p class="card-text mb-2">Price: <%= item['price'] %> $</p>
                    <% if Current.user.admin? %>
                      <%= form_tag update_order_item_quantity_path(@order, item['item_id']), method: :patch, class: "mb-2" do %>
                        <%= number_field_tag "item[quantity]", item['quantity'], class: "form-control form-control-sm text-center", min: 1 %>
                        <%= submit_tag "Update", class: "btn btn-primary btn-sm mt-2 form-control" %>
                      <% end %>
                      <%= button_to "Delete", delete_order_item_path(order_id: @order.id, item_id: item['item_id']), method: :delete, data: { confirm: "Are you sure you want to delete this item from the order?" }, class: "btn btn-danger btn-sm form-control" %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
            <div class="row mt-3">
              <div class="col-md-12">
                <p><strong>Total Amount:</strong> <%= @order.total_amount %> $</p>
                <p><strong>Order Date:</strong> <%= @order.order_date.strftime("%B %d, %Y %H:%M") %></p>
                <% if Current.user.admin? %>
                  <%= form_for(@order, url: update_order_status_path(@order), method: :patch) do |f| %>
                    <%= f.select :status, @order_statuses.invert, class: "form-control mb-2" %>
                    <%= f.submit "Update Status", class: "btn btn-primary btn-sm" %>
                  <% end %>
                  <% if @order.status == "pending" %>
                    <%= button_to "Cancel Order", cancel_order_path(@order), method: :patch, data: { confirm: "Are you sure you want to cancel this order?" }, class: "btn btn-danger btn-sm" %>
                  <% end %>
                <% else %>
                  <p><strong>Status:</strong> <%= @order.status %></p>
                  <% if @order.status == "pending" %>
                    <%= button_to "Cancel Order", cancel_order_path(@order), method: :patch, data: { confirm: "Are you sure you want to cancel this order?" }, class: "btn btn-danger btn-sm" %>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% else %>
            <p>Order not found</p>
          <% end %>
          <div class="row mt-3">
            <div class="col-md-12">
              <%= link_to 'Back', orders_path, class: "btn btn-secondary" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>